export const types = {
    // Calculator types
    INPUT_NUMBER: 'INPUT_NUMBER',
    ADD_OPERATION: 'ADD_OPERATION',
    SUBTRACT_OPERATION: 'SUBTRACT_OPERATION',
    MULTIPLY_OPERATION: 'MULTIPLY_OPERATION',
    DIVIDE_OPERATION: 'DIVIDE_OPERATION',
    CLEAR_LIST: 'CLEAR_LIST'
}

